version: '3'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - /volume1/docker/homeassistant/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - tcp://192.168.50.151:5000:/tcp://192.168.50.151:5000
    restart: always
    network_mode: host
    privileged: true
    restart: always
    environment:
      - TZ=Europe/Oslo

  mosquitto:
    image: eclipse-mosquitto
    restart: always
    network_mode: host
    volumes:
      - /volume1/docker/mosquitto/config:/mosquitto/config/
      - /volume1/docker/mosquitto/data:/mosquitto/data
      - /volume1/docker/mosquitto/log:/mosquitto/log
